### ISSUE TITLE
Parslet gem

### ISSUE THREAD

**Issue by logicrime** [diasks2/ruby-nlp#11]
Treetop is over 2 years unmaintained, and Parslet is actively maintained. Most recent commit was a few weeks ago.

Parslet is also easier to use than Treetop, and faster as well if I recall correctly.

**Comment by diasks2** [comment]
Thanks! Added it in: https://github.com/diasks2/ruby-nlp/commit/e93d29a22f55043ad9a24dbd7e4d58fcc9347584
