### ISSUE TITLE
API.ai Ruby wrapper

### ISSUE THREAD

**Issue by solyarisoftware** [diasks2/ruby-nlp#18]
Hi Kevin,
here a new item I'd suggest to add in this directory, maybehere:
https://github.com/diasks2/ruby-nlp/#3rd-party-nlp-services
- [A Ruby SDK to the https://api.ai natural language processing service](https://github.com/api-ai/api-ai-ruby)

text: A Ruby SDK to the https://api.ai natural language processing service
url: https://github.com/api-ai/api-ai-ruby

BTW, https://api.ai is something similar to wit.ai. 
At frst glance API.ai well documented and partially free.

**Comment by diasks2** [comment]
Thanks! Added it: https://github.com/diasks2/ruby-nlp/commit/8037fe401b90838a5c91eed67b65b70ee35bb2f3 :+1:
