### ISSUE TITLE
Add sastrawi-ruby

### ISSUE THREAD

**Issue by meisyal** [diasks2/ruby-nlp#26]
Hi, Kevin!

I would to add [sastrawi-ruby](https://github.com/meisyal/sastrawi-ruby) to this awesome list. sastrawi-ruby is a library which allows you to stem words in Bahasa Indonesia. Basically, it's a stemmer.
What do you think?

I am sorry, I can't fork this repository and make a pull request.

**Comment by diasks2** [comment]
Thank you for the suggestion! I added that: https://github.com/diasks2/ruby-nlp/commit/5f0ce804e8e67dda77cee82ee61ed78163601fd0
