### ISSUE TITLE
How about Treetop gem?

### ISSUE THREAD

**Issue by glaucocustodio** [diasks2/ruby-nlp#6]
A while ago I used https://rubygems.org/gems/treetop to make a natural language parser.. I also made a blog post: http://blog.glaucocustodio.com/2014/11/10/natural-language-parsing-with-ruby/.

I did not find this gem in the readme.

**Comment by diasks2** [comment]
Thanks for the suggestions! I added both in this commit: https://github.com/diasks2/ruby-nlp/commit/9bb30fb168b3a4ab675a27a588bb14310ed29670
