### ISSUE TITLE
Nameable

### ISSUE THREAD

**Issue by chorn** [diasks2/ruby-nlp#7]
I love this list!

You might like a gem I wrote, [nameable](https://github.com/chorn/nameable). Not too long ago I added some datasets from the US Census and US Social Security Administration that will make a best guess towards the ethnicities and gender of a person's name.

I have another gem, [dialable](https://github.com/chorn/dialable), that uses the offical North American (US & Canada) area code database, and will find zip codes.

My feelings will not be hurt if you don't include them. :)

**Comment by diasks2** [comment]
Thanks! I'd be happy to add them. If you create a pull request I'll merge it in, or I can add them in. Either way.

**Comment by diasks2** [comment]
https://github.com/diasks2/ruby-nlp/commit/fc9b54960eab7d5b1e7830b35c4e39c46d5d5fae
